name: BW
favicon: null
layout_spectrum: 0.4783436693251133
typography_spectrum: 0.6952641985844821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.46338995546102524
  lightness: 0.5166092447470874
  saturation: 0.9895623729098588
  rhythmicContrast: 0.1496942436788231
purpose: []
